### PR TITLE
feat(TSCH-37): set button min-height inside navbar

### PR DESCRIPTION
**Pull request by amaalej**
**Please check if the PR fulfills these requirements**

- [ ] The commit(s) message(s) follows our [guidelines](https://github.com/Talend/bootstrap-theme/blob/master/CONTRIBUTING.md#commit-message-format)
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?**

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [x] Refactoring (no functional changes, no api changes)
- [ ] Build / CI related changes
- [ ] Other... Please describe:

**What is the current behavior?**
Inserting a button inside navbar results into a wrong display due to button size.

**What is the new behavior?**
I set the button size to the navbar one.

**Does this PR introduce a breaking change?**

- [ ] Yes
- [x] No

**Other information**:
I need it for the search button which shows the Typeahead once clicked. (it's an action not a navigation)

### CODE REVIEW

**Comment by frassinier** [comment]
Could you please attach documentation about that role please?

**Comment by amaalej** [comment]
@frassinier it's the search box mockup. [Guidelines](http://guidelines.talend.com/document/92132#/navigation-layout/search-bar)

**Comment by frassinier** [comment]
No, I would like to reach doc about `role="action"` please?

**Comment by amaalej** [comment]
oh, I will change it to role="search"

**Pull request merged**
