### PR TITLE
fix: input-group-btn line-height

### PR DESCRIPTION
**Pull request by frassinier**
Fix `.input-group-btn` special line-height to match to the controls one.

before

vs

after

### CODE REVIEW

**Comment by jmfrancois** [comment]
What was the behavior before the change please ?

**Comment by frassinier** [comment]
You right, at least, I can produce a before and after to display diff, I edited my first post.

**Comment by jmfrancois** [comment]
In fact I don't understand that change.
It looks like a fix but the PR title let think about it's a enhancement (Add ...)
I'm sure the previous behavior you show is not the bootstrap one normal behavior. There are many examples like this one 
screen shot 2016-09-13 at 15 29 17

Could you show me the HTML snippet corresponding to this example ? May be on a plunkr or some other service where we could discuss the things ?

**Comment by frassinier** [comment]
Jean-Michel, here is my override to apply a smaller font-size to all buttons https://github.com/Talend/bootstrap-theme/blob/master/src/theme/_buttons.scss#L8

So, yes, it's a fix to correct buttons height next to an input.

**Comment by talend-glorieux** [comment]
LGTM

**Pull request merged**
