### PR TITLE
feat(TPSVC-851/colors): add common colors

### PR DESCRIPTION
**Pull request by slavasel**
**Please check if the PR fulfills these requirements**

- [x] The commit(s) message(s) follows our [guidelines](https://github.com/Talend/bootstrap-theme/blob/master/CONTRIBUTING.md#commit-message-format)
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?**

- [ ] Bugfix
- [x] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build / CI related changes
- [ ] Other... Please describe:

**What is the current behavior?** (You can also link to an open issue here)

**What is the new behavior?**
Add $concrete, $black, $white color vars.

**Does this PR introduce a breaking change?**

- [ ] Yes
- [x] No

If this PR contains a breaking change, please describe the impact and migration path for existing applications: ...

**Other information**:

### CODE REVIEW

**Comment by jsomsanith** [comment]
Can you explain why we need those variables ?

**Comment by slavasel** [comment]
Sure, we used to have $white and $black colors in TPSVC for titles, background etc. For the $concrete (#F2F2F2), it was used for navpanel.
All the added colors and names of the variables honours the guidelines:
http://guidelines.talend.com/d/xawdeLsCK7Vn/talend-style-guide#/ui-controls/find

**Comment by jsomsanith** [comment]
So I think this should not be translated into $white, $black, $concrete. It should have vars names that is meaningfull for the component that you will customize, and customize it in the bootstrap-theme or react-CMF-bootstrap.
Any recommandation @frassinier ?

**Comment by frassinier** [comment]
No we must follow Frontify names in order to link this project and our guidelines. 
I approved thiis PR even if I think blck and white is pretty useless since they will not change I guess but why not.

**Comment by ftom** [comment]
can you add the missing colors, I count 9 in the file while frontify list 12 of them ?

**Comment by slavasel** [comment]
This is done. I've opened a new PR with adding left colors and ordering

**Comment by ftom** [comment]
GJ

**Pull request merged**
