### PR TITLE
doc: Add how to part

### PR DESCRIPTION
**Pull request by frassinier**

### CODE REVIEW

**Comment by jsomsanith** [comment]
About the `npm install` part, what is the publication plan ?
Do we publish on npm ? or nexus-npm ?

**Comment by acateland** [comment]
This is solely targeted to build our applications, and apply our brand on to them so, installation on nexus-npm id say.

**Comment by acateland** [comment]
lgtm

**Comment by talend-glorieux** [comment]
LGTM

**Comment by frassinier** [comment]
Thanks guys, 
Thanks @talend-glorieux for highlighting!
You're right, I did not publish it to Nexus yet. 
We can install with `npm i -S Talend/bootstrap-theme` to follow master for now.

**Pull request merged**
