### PR TITLE
docs: Generate examples and documentation from Travis CI

### LINKED ISSUE #7: Create a GitHub page with examples and documentation
Adding a GitHub page containing live example of components would make it easier for developers and designers to mockup, test and improve the components.

Adding the [generated sass-doc](http://sassdoc.com/) could also be a good thing.

### PR DESCRIPTION
**Pull request by frassinier**
Closes #7

### CODE REVIEW

**Comment by talend-glorieux** [comment]
Looks good. Is there a way to try it before merging into master ?

**Comment by frassinier** [comment]
Sure, by restarting Tavis build. It will update `gh-pages` branch. 
I previously merge some stuff to master then `gh-pages` was updated.

[Here is the result](https://talend.github.io/bootstrap-theme/)

**Comment by frassinier** [comment]
And this is why I want to merge it ASAP! :)

**Comment by talend-glorieux** [comment]
OK Go ahead and merge it. We'll improve it later ;)

**Comment by frassinier** [comment]
Thank you @talend-glorieux

**Pull request merged**
