### PR TITLE
[WIP] feat: Add PhantomCSS dependency to generate screenshots

### PR DESCRIPTION
**Pull request by frassinier**
[PhantomCSS](https://github.com/Huddle/PhantomCSS) permits visual regression testing with PhantomJS.

I don't know how to do that for now but
I propose to commit screenshots as referential.
If a pull request introduces a visual regression then the diff could be commited by Travis into the branch (marked as modified file) 

@Talend/frontend What do you think about it?

### CODE REVIEW

**Comment by talend-glorieux** [comment]
I think it's a great idea. I already did something similar some time ago.
The only thing that can create issues is commiting the screenshots directly to Git. It's usually better to use something like Git-LFS when storing big assets.

**Comment by frassinier** [comment]
My first idea is to let Travis completes the PR, not create issue:

1. Create a PR
2. Run tests from Travis
3. If a diff is generated then commit the diff to the branch
4. Diff appears in PR as modified file in order to be validated as new referential if PR is merged

**Comment by talend-glorieux** [comment]
My bad ;)
What I meant by issue(problem) was that committing images to the branch will in the long run increase the repository size. That's my only concern. I'm OK with the idea and the workflow.

**Comment by frassinier** [comment]
Oh sorry, I read your post too quickly! 

I'm not sure that small PNG is considered as big files.
And do you if Git-LFS can be linked to a PR?

**Comment by talend-glorieux** [comment]
I'll have to check.

**Pull request closed without merging**
