### PR TITLE
feat(TPSVC-1087/fonts): add fonts

### PR DESCRIPTION
**Pull request by slavasel**
**Please check if the PR fulfills these requirements**

- [x] The commit(s) message(s) follows our [guidelines](https://github.com/Talend/bootstrap-theme/blob/master/CONTRIBUTING.md#commit-message-format)
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?**

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build / CI related changes
- [ ] Other... Please describe:

**What is the current behavior?** (You can also link to an open issue here)

**What is the new behavior?**

**Does this PR introduce a breaking change?**

- [ ] Yes
- [x] No

If this PR contains a breaking change, please describe the impact and migration path for existing applications: ...

**Other information**:

### CODE REVIEW

**Comment by frassinier** [comment]
Thanks @slavasel but this font is already a [project dependency](https://github.com/Talend/bootstrap-theme/blob/master/package.json#L47). 
You have to build it with Webpack, [here is an example](https://github.com/Talend/bootstrap-theme/blob/master/webpack.config.js#L26)

**Comment by slavasel** [comment]
@frassinier, as I understand, you mean "Source Sans Pro" is already added to the repo. But what about "icons-font.woff". Can we add them? Thanks!

**Comment by frassinier** [comment]
It's not yet decided, for now, if each project will have to include its own icon font, if all projects will use FontAwesome or if we will include icon font for all.
 
By the way, if the choice is to include icon font for all, I think it cool be cool to have another Github repo for that.  

@Talend/frontend What do you think?

**Comment by acateland** [comment]
Yeah if we are going down the path to have a common icon font for all projects it should live in its own repo for easier maintenance/release process

**Comment by slavasel** [comment]
Guys, thank you! Will close this PR, as it's not necessary.

**Comment by frassinier** [comment]
Thanks @slavasel

**Pull request closed without merging**
