### PR TITLE
[WIP] feat: Generate style variations from fixtures and upload them to Frontify

### PR DESCRIPTION
**Pull request by frassinier**
Replace _example_ folder by _fixtures_ in order to produce many themes as applications using this custom Bootstrap theme.

### CODE REVIEW

**Comment by jmfrancois** [comment]
could you explain what do you mean by fixture ?

**Comment by frassinier** [comment]
Fixtures are hard coded pieces of code. The aim is to push them into a referential, we can easily imagine to deploy them to Frontify.  

Here is an [example](https://github.com/frassinier/frontify-bootstrap).

**Comment by talend-glorieux** [comment]
@frassinier I really like the idea of turning the examples into something close to tests.

**Comment by jmfrancois** [comment]
Frontify do not support this ATM.
Let's look at this later;

**Pull request closed without merging**
