### PR TITLE
feat(dropdown): change dropdown caret

### PR DESCRIPTION
**Pull request by mtikhinskaya**
**Please check if the PR fulfills these requirements**

- [x] The commit(s) message(s) follows our [guidelines](https://github.com/Talend/bootstrap-theme/blob/master/CONTRIBUTING.md#commit-message-format)
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?**

- [ ] Bugfix
- [x] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build / CI related changes
- [ ] Other... Please describe:

**What is the current behavior?** (You can also link to an open issue here)

The current dropdown icon use pure CSS as bootstrap does

**What is the new behavior?**

the icon are delivered by UX team in SVG;
it fix PhantomJS problems.

**Does this PR introduce a breaking change?**

- [ ] Yes
- [x] No

If this PR contains a breaking change, please describe the impact and migration path for existing applications: ...

### CODE REVIEW

**Comment by jsomsanith** [comment]
Hi @mtikhinskaya,
Can you explain what is the motivation behind this PR ? Because the current caret is pretty elegant and lightweight, using only 2 borders with the right rotation.
I don't see any benefit using svg which code is contained in scss, and duplicated in the generated file.

**Comment by jmfrancois** [comment]
on master:
bootstrap.css   175 kB       0  [emitted]  main
bootstrap.min.css   148 kB       0  [emitted]  main

on this branch:
bootstrap.css  179 kB       0  [emitted]  main
bootstrap.min.css  152 kB       0  [emitted]  main

**Comment by mtikhinskaya** [comment]
I prefer to use svg icon instead of border because:
- the icon was delivered by UX team;
- the tree view icon will be the same;
- it will fix PhantomJS problems.
If you afraid of performance I checked the average time of loading and it change only on  1ms (but it can be a calculation fault). Also we have navbar brand icon also in base64: https://github.com/Talend/bootstrap-theme/blob/master/src/theme/_navbar.scss#L28

**Comment by jsomsanith** [comment]
* the icon was delivered by UX team : ok but the usecases, this is not recommanded. The css reproduce exactly what the ux team want
* the tree view icon will be the same : we can use the svg here with the <Icon> component
* it will fix PhantomJS problems : what problem ?

**Comment by frassinier** [comment]
It's a really good idea (but not for this repository).
 
IMHO, I think it should be in [Talend/icons](https://github.com/Talend/icons) for generating a CSS file in order to be used with pseudo elements (e.g. `:before` or `:after`).

If I added base 64 encoded image for our logo is to not dealing with assets and to keep network trafic as simple as possible. And it's appear one time in your final CSS for all projects :roll_eyes:

**Comment by jmfrancois** [comment]
It could not be just an override of the caret class ?

**Comment by jsomsanith** [comment]
I duplication (the mixin in fact) is about changing the color

**Comment by frassinier** [comment]
(I'm tryin to fix Travis script #79 in order to produce screenshots)

**Comment by frassinier** [comment]
I closed. Feel free to reopen if you really want this to be merge in order to be rediscussed.

**Pull request closed without merging**
